spring:
  profiles:
    active: dev

---
spring:
  application:
    name: client1
  config:
    activate:
      on-profile: dev
server:
  port: 7005
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: 1111
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

---
spring:
  application:
    name: client2
  config:
    activate:
      on-profile: test
server:
  port: 7006
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: 2222
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/
