spring:
  profiles:
    active: dev
---
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/, http://localhost:7003/eureka/
spring:
  application:
    name: user-service1
  config:
    activate:
      on-profile: dev
---
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/, http://localhost:7002/eureka/, http://localhost:7003/eureka/
spring:
  application:
    name: user-service2
  config:
    activate:
      on-profile: test
